[http.status]
sessions = 128
ttl-hrs = 48

[limits]
fd = 8192

[sync]
poll-sec = 1.0
ping-sec = 3.5

[ttl]
enable = true
period-hrs = 24
noise = 0.3

[updates]
url = "https://raw.githubusercontent.com/aspectron/kaspa-resolver/master/data/"
duration-hrs = 12.0

